### ISSUE TITLE
请问GTZAN数据集的标记是否没有.beat文件？

### ISSUE THREAD

**Issue by czfandyslash** [zdyshine/beat_track_mgtv_baseline#1]
根据指引下载了GTZAN的标记数据，发现只有jam文件里有对beat和downbeat的标记数据，想咨询一下是否有.beat .downbeat格式的文件可下载，还是说需要再自己提取一下？
谢谢！

**Comment by zdyshine** [comment]
需要自己提取

**Comment by czfandyslash** [comment]
感谢答复，已自行解决～
